<a href="https://colab.research.google.com/github/raven-gith/machinelearning1/blob/main/16.%20Chapter%2016/chapter_16_nlp_rnn_attention.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 16: Natural Language Processing with RNNs and Attention

Notebook ini mereproduksi dan menjelaskan isi Bab 16 dari buku _Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow_ oleh Aurélien Géron.

## 📘 Ringkasan Materi:

Bab ini membahas penggunaan RNN dan attention mechanism untuk **Natural Language Processing (NLP)**.

### Materi utama:
1. Tokenisasi dan padding teks dengan `TextVectorization`
2. Model NLP dengan Embedding + RNN
3. Bidirectional LSTM untuk teks
4. Attention Mechanism (konsep dasar)


In [1]:

import tensorflow as tf
from tensorflow import keras
import numpy as np

# Contoh kalimat
texts = ["Aku suka belajar machine learning", "Deep learning sangat menarik", "Saya tidak suka spam"]

# Text vectorization layer
vectorizer = keras.layers.TextVectorization(max_tokens=1000, output_sequence_length=6)
text_ds = tf.data.Dataset.from_tensor_slices(texts).batch(1)
vectorizer.adapt(text_ds)

# Cek hasil tokenisasi
vectorized_texts = vectorizer(texts)
print(vectorized_texts.numpy())


[[12  2 11  9  3  0]
 [10  3  7  8  0  0]
 [ 6  4  2  5  0  0]]


In [2]:

# Dataset dummy (vektorisasi output = binary sentiment)
X = vectorized_texts.numpy()
y = np.array([1, 1, 0])  # 1 = positif, 0 = negatif

model = keras.Sequential([
    keras.layers.Embedding(input_dim=1000, output_dim=16, input_length=6),
    keras.layers.Bidirectional(keras.layers.LSTM(16)),
    keras.layers.Dense(1, activation="sigmoid")
])

model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])
model.fit(X, y, epochs=10)


Epoch 1/10


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 7s 7s/step - accuracy: 0.6667 - loss: 0.6934
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 210ms/step - accuracy: 0.6667 - loss: 0.6910
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step - accuracy: 0.6667 - loss: 0.6887
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.6667 - loss: 0.6864
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.6667 - loss: 0.6841
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.6667 - loss: 0.6818
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.6667 - loss: 0.6795
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.6667 - loss: 0.6771
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.6667 - loss: 0.6747
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.6667 - loss: 0.6723



##  Konsep Attention (Dasar)

**Attention mechanism** memungkinkan model memfokuskan perhatian ke bagian input yang paling relevan saat memproses sekuens panjang.  
Secara umum, attention menghitung skor bobot dari setiap bagian input, lalu menggabungkannya secara dinamis berdasarkan konteks.

 Contoh: Digunakan di Transformer, BERT, dan banyak model NLP modern.

Implementasi lengkap attention tidak dibahas di bab ini, tapi akan muncul di bab selanjutnya.
